### ISSUE TITLE
Outdated Ingress configuration

### ISSUE THREAD

**Issue by azuk-bread** [vfarcic/k8s-specs#18]
All of the `Ingress` objects are using outdated syntax that doesn't work with the latest version of kube at the time of this writing.

In particular, the following changes need to be made to all `Ingress` object configs:
- the value of `apiVersion` should be changed to `networking.k8s.io/v1`
- `pathType` is now required next to `path`
- `serviceName` and `servicePort` are deprecated and should instead be replaced w/ something like this:
```yaml
service:
    name: foo
    port:
        number: 8080
```
